banner:
  location: classpath:config/banner.txt
flyway:
  enabled: true
  url: ${spring.datasource.url}
  validate-on-migrate: true
  schemas: blogblog
spring:
  datasource:
    username: blog_user
  jooq:
    sql-dialect: postgres
  jackson:
    serialization:
      indent_output: true