banner:
  location: classpath:config/banner.txt
flyway:
  enabled: true
  url: ${spring.datasource.url}
  validate-on-migrate: true
  schemas: blogblog
spring:
  datasource:
    username: blog_user
  jooq:
    sql-dialect: postgres
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_dates_with_zone_id: true
  hateoas:
    use-hal-as-default-json-media-type: true