/**
 * This class is generated by jOOQ
 */
package de.blogblog.jooq.tables.records;


import de.blogblog.jooq.tables.BlPosts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlPostsRecord extends UpdatableRecordImpl<BlPostsRecord> implements Record6<Integer, String, String, Timestamp, Integer, Boolean> {

    private static final long serialVersionUID = 482934652;

    /**
     * Setter for <code>blogblog.bl_posts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blogblog.bl_posts.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blogblog.bl_posts.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blogblog.bl_posts.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>blogblog.bl_posts.author</code>.
     */
    public void setAuthor(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.author</code>.
     */
    public Integer getAuthor() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>blogblog.bl_posts.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Integer, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BlPosts.BL_POSTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BlPosts.BL_POSTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BlPosts.BL_POSTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return BlPosts.BL_POSTS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return BlPosts.BL_POSTS.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return BlPosts.BL_POSTS.HIDDEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getHidden();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value5(Integer value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value6(Boolean value) {
        setHidden(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord values(Integer value1, String value2, String value3, Timestamp value4, Integer value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlPostsRecord
     */
    public BlPostsRecord() {
        super(BlPosts.BL_POSTS);
    }

    /**
     * Create a detached, initialised BlPostsRecord
     */
    public BlPostsRecord(Integer id, String title, String content, Timestamp created, Integer author, Boolean hidden) {
        super(BlPosts.BL_POSTS);

        set(0, id);
        set(1, title);
        set(2, content);
        set(3, created);
        set(4, author);
        set(5, hidden);
    }
}
