/**
 * This class is generated by jOOQ
 */
package de.blogblog.jooq.tables.records;


import de.blogblog.jooq.tables.BlPosts;

import java.time.ZonedDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlPostsRecord extends UpdatableRecordImpl<BlPostsRecord> implements Record7<Integer, String, String, String, ZonedDateTime, Integer, Boolean> {

    private static final long serialVersionUID = -1889165397;

    /**
     * Setter for <code>blogblog.bl_posts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blogblog.bl_posts.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blogblog.bl_posts.static_link</code>.
     */
    public void setStaticLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.static_link</code>.
     */
    public String getStaticLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blogblog.bl_posts.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blogblog.bl_posts.created</code>.
     */
    public void setCreated(ZonedDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.created</code>.
     */
    public ZonedDateTime getCreated() {
        return (ZonedDateTime) get(4);
    }

    /**
     * Setter for <code>blogblog.bl_posts.author</code>.
     */
    public void setAuthor(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.author</code>.
     */
    public Integer getAuthor() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>blogblog.bl_posts.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>blogblog.bl_posts.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, ZonedDateTime, Integer, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, ZonedDateTime, Integer, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BlPosts.BL_POSTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BlPosts.BL_POSTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BlPosts.BL_POSTS.STATIC_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BlPosts.BL_POSTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ZonedDateTime> field5() {
        return BlPosts.BL_POSTS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BlPosts.BL_POSTS.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return BlPosts.BL_POSTS.HIDDEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStaticLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZonedDateTime value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getHidden();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value3(String value) {
        setStaticLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value5(ZonedDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value6(Integer value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord value7(Boolean value) {
        setHidden(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlPostsRecord values(Integer value1, String value2, String value3, String value4, ZonedDateTime value5, Integer value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlPostsRecord
     */
    public BlPostsRecord() {
        super(BlPosts.BL_POSTS);
    }

    /**
     * Create a detached, initialised BlPostsRecord
     */
    public BlPostsRecord(Integer id, String title, String staticLink, String content, ZonedDateTime created, Integer author, Boolean hidden) {
        super(BlPosts.BL_POSTS);

        set(0, id);
        set(1, title);
        set(2, staticLink);
        set(3, content);
        set(4, created);
        set(5, author);
        set(6, hidden);
    }
}
