/**
 * This class is generated by jOOQ
 */
package de.blogblog.jooq;


import de.blogblog.jooq.tables.BlPosts;
import de.blogblog.jooq.tables.BlUsers;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blogblog extends SchemaImpl {

    private static final long serialVersionUID = -1551587978;

    /**
     * The reference instance of <code>blogblog</code>
     */
    public static final Blogblog BLOGBLOG = new Blogblog();

    /**
     * The table <code>blogblog.bl_posts</code>.
     */
    public final BlPosts BL_POSTS = de.blogblog.jooq.tables.BlPosts.BL_POSTS;

    /**
     * The table <code>blogblog.bl_users</code>.
     */
    public final BlUsers BL_USERS = de.blogblog.jooq.tables.BlUsers.BL_USERS;

    /**
     * No further instances allowed
     */
    private Blogblog() {
        super("blogblog", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BlPosts.BL_POSTS,
            BlUsers.BL_USERS);
    }
}
