/**
 * This class is generated by jOOQ
 */
package de.blogblog.jooq;


import de.blogblog.jooq.tables.BlPosts;
import de.blogblog.jooq.tables.BlUsers;
import de.blogblog.jooq.tables.records.BlPostsRecord;
import de.blogblog.jooq.tables.records.BlUsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>blogblog</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BlPostsRecord, Integer> IDENTITY_BL_POSTS = Identities0.IDENTITY_BL_POSTS;
    public static final Identity<BlUsersRecord, Integer> IDENTITY_BL_USERS = Identities0.IDENTITY_BL_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BlPostsRecord> PK_POSTS = UniqueKeys0.PK_POSTS;
    public static final UniqueKey<BlPostsRecord> UQ_POSTS_STATIC_LINK = UniqueKeys0.UQ_POSTS_STATIC_LINK;
    public static final UniqueKey<BlUsersRecord> PK_USERS = UniqueKeys0.PK_USERS;
    public static final UniqueKey<BlUsersRecord> UQ_USERS_USERNAME = UniqueKeys0.UQ_USERS_USERNAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BlPostsRecord, BlUsersRecord> BL_POSTS__FK_POSTS_AUTHOR = ForeignKeys0.BL_POSTS__FK_POSTS_AUTHOR;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BlPostsRecord, Integer> IDENTITY_BL_POSTS = createIdentity(BlPosts.BL_POSTS, BlPosts.BL_POSTS.ID);
        public static Identity<BlUsersRecord, Integer> IDENTITY_BL_USERS = createIdentity(BlUsers.BL_USERS, BlUsers.BL_USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BlPostsRecord> PK_POSTS = createUniqueKey(BlPosts.BL_POSTS, "pk_posts", BlPosts.BL_POSTS.ID);
        public static final UniqueKey<BlPostsRecord> UQ_POSTS_STATIC_LINK = createUniqueKey(BlPosts.BL_POSTS, "uq_posts_static_link", BlPosts.BL_POSTS.STATIC_LINK);
        public static final UniqueKey<BlUsersRecord> PK_USERS = createUniqueKey(BlUsers.BL_USERS, "pk_users", BlUsers.BL_USERS.ID);
        public static final UniqueKey<BlUsersRecord> UQ_USERS_USERNAME = createUniqueKey(BlUsers.BL_USERS, "uq_users_username", BlUsers.BL_USERS.USERNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BlPostsRecord, BlUsersRecord> BL_POSTS__FK_POSTS_AUTHOR = createForeignKey(de.blogblog.jooq.Keys.PK_USERS, BlPosts.BL_POSTS, "bl_posts__fk_posts_author", BlPosts.BL_POSTS.AUTHOR);
    }
}
