/**
 * This class is generated by jOOQ
 */
package de.blogblog.jooq;


import de.blogblog.jooq.tables.BlPosts;
import de.blogblog.jooq.tables.BlUsers;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in blogblog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blogblog.bl_posts</code>.
     */
    public static final BlPosts BL_POSTS = de.blogblog.jooq.tables.BlPosts.BL_POSTS;

    /**
     * The table <code>blogblog.bl_users</code>.
     */
    public static final BlUsers BL_USERS = de.blogblog.jooq.tables.BlUsers.BL_USERS;
}
